---
title: A Deep Dive into `allometric`
author: Bryce Frank
---

This article is for people who are interested in fully understanding the 
internal structure of `allometric`. I begin first with some motivating ideas and
then demonstrate how those ideas result in certain choices for the package
structure.

# Motivating Ideas

`allometric` is inspired by a number of existing packages including the 
National Volume Estimator Library, FVS, and ORGANON. These packages, to some 
extent or another, implement allometric equations for the purposes of tree-level
volume predictions, taper, growth modeling, etc. However, the scope of these 
software is geographically constrained to the United States, and the structure
of the database may require agency-specific data such as USFS Forest or Region.

In my work as a 
consulting biometrician, I have found a need for a "database" of sorts for 
allometric equations at a global scale. I should be able to make a volume 
prediction for Norway spruce just as easily as Ponderosa pine. Ideally, that 
software would be centralized, and should provide clear connections to the 
scientific literature for a given species. That way, I can check the paper to
verify the volume model if I want to. In sum, this ideal software would:

1. Enable easy and clear searching of allometric equations by response variable,
geographic region, and species for a global set of models.
2. Provide a citation for every model in the package.
3. Provide easy-to-use prediction functions, with clear requirements for their
use, such as information about needed covariates and their measurement units.

In many ways, my first allometric modeling package [forvol](https://github.com/brycefrank/forvol)
was an attempt at these three objectives. However, the package was flawed from
the beginning, since it heavily relied on USFS-FIA specification files, which 
naturally constrained the package to the United States. It also considered only
volume functions, and not the more general setting of allometric models.

`forvol` was also fairly complicated in its structure. It required intimate 
knowledge of NVEL equation codes and editing several specification files 
simultaneously. A true open source platform for allometric equations should 
*facilitate* open source contributions. This led to the fourth objective

4. Allow for biometricians familiar with R a (relatively) easy way to contribute
to the addition of allometric equations.

# Package Structure

With these objectives in mind, the package structure began to take shape over 
a number of weeks. It was clear from objective 2. that publications needed to
be an intimate component of the package. In fact, the `Publication` class is
the primary entry point into adding models. `Publication` objects will contain
"children" called `ModelSet`s and in turn `ModelSet`s contain `Model` objects.
Using this structure, allometric models are intimately tied with their 
source publication.
