---
title: "Describing a Model with Descriptors"
---

Descriptors are sets of information that describe a model, model set or
publication. Descriptors are *optional* under one condition, all models within
a `ModelSet` must be uniquely identified by the set of descriptors. So, for a
`ModelSet` containing one model, no descriptors are needed.

However, authors are encouraged to define a set of *search descriptors* if able.
These descriptors are propagated to the `model_filter` function and allow for
quick filtering of allometric equations

The set of *search descriptors* are:
- `country` - the country (or countries) of the dataset used for the
model. Countries must be two-character 
[ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) names.
- `region` - the region of the dataset used for the model. Regions are defined
as subsets of countries, and must comply with the four-character region codes
given in [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2). States are 
an example of regions, e.g., "US-CO" for Colorado, US.
- `family` - the taxonomic family of the dataset used for the model.
- `genus` - the taxonomic genus of the dataset used for the model.
- `species` - the taxonomic species of the dataset used for the model.

TODO - add more as they come up.
