---
title: "Installing a Model"
---

Models can be installed by anyone, provided they are comfortable writing R and
submitting `git` pull requests. The model installation process involves these
basic steps.

1. Fork and then clone the `allometric` git repository to your local enviroment.
2. Write a new file in the `R` directory that
    a. Establishes a citation for the originating publication of the model.
    b. Instantiates the model (usually a `ParametricModel` or
        `ParametricFamily`) with associated metadata and prediction function.
3. Add and commit the new file to the remote forked repository from (1)
4. Submit a pull request to `brycefrank/allometric` via GitHub.

After the completion of step 4, your pull request will be tested and reviewed
for completion, and will become part of the main package if it passes review.

This vignette will focus on the second step. Explanation of `git` pull requests
are beyond the scope of this vignette, but interested readers can learn using
[these resources #TODO]. Interested readers should also contact Bryce Frank
(bfrank70@gmail.com), or open an issue on GitHub if they want their models 
added but do not want to learn `git`.

## Establishing a Publication

`allometric::Publication` is a class that represents a given scientific article,
report, or other technical document that contains allometric models. 

Citations are established using `RefManageR::BibEntry` which is an R 
representation of a BibTex citation. For example, the BibEntry for the following
publication

H. Temesgen, V. J. Monleon, and D. W. Hann. "Analysis and comparison of nonlinear tree height prediction strategies for Douglas-fir forests". In: _Canadian
Journal of Forest Research_ 38.3 (2008), pp. 553-565.

is

```
paper_citation <- RefManageR::BibEntry(
    bibtype = 'article',
    key = 'temesgen_2008',
    title = 'Analysis and comparison of nonlinear tree height prediction
        strategies for Douglas-fir forests',
    author = 'Temesgen, Hailemariam and Monleon, Vicente J. and Hann, David W.',
    journal = 'Canadian Journal of Forest Research',
    year = 2008,
    volume = 38,
    number = 3,
    pages = '553-565',
    year = 2008
)
```

many different types of publications are available, called "entry types", and 
documentation for required fields are given
[here](https://www.bibtex.com/e/entry-types/).

## Instantiating a Single Model

## Instantiating a Model Set with
