---
title: "Mixed-Effects Models"
---

Mixed-effects models are common in the allometric modeling literature, and
allow "calibration" of models at different levels of aggregation, such as 
field plots and stands. `allometric` supports mixed effects modeling with the 
`MixedEffectsModel` class. However, due to the highly technical nature of this topic,
this vignette highlights a few important concerns that authors should be aware
of  before proceeding with a mixed-effects model implementation.

## Navigating Published Mixed Effects Models

Implementing published mixed-effects models is, strictly speaking, 
possible in `allometric`. However, predictions for groups with
random parameters (e.g., field plots or stands) require knowledge of the 
estimated variance-covariance matrix of the random parameters themselves
[cite]. As well, partial derivatives of the model with respect to the
fixed-effects parameters are needed. These two components are not always
explicitly provided in publications. 

Because `allometric` directly cites publications and implements models from 
them, it is best practice to only implement what is explicitly published, 
rather than derive un-published portions of the models. @temesgen_2008 is one
such example where the derivatives are evalutated (p. 557), while @sharma_2007
is an example where the derivatives are not evaluated (Section 2.4). Using this
approach, the mixed-effects models in @temesgen_2008 are appropriate for
`allometric` but  the mixed-effects models in @sharma_2007 are not, since the 
final model form is not strictly provided in the publication.

Alternatively, predictions from mixed-effects models can be generated using the
fixed-effects estimates only [cite], which are often reported.. In fact, many studies will assess the
performance of a mixed-effects model in this way, and the utility of using the
fixed-effects estimates is obvious when observations from a new "target group"
are not available. However, this activity does deviate from the purest intent of
the model, and should be explicitly flagged in `allometric` by installing a
`MixedEffectsModel` class with the argument `fixed_only = TRUE` to denote
that only the fixed-effects are generating the predictions. This argument is
propagated to further documentation and model summaries to alert users to this
special case.

Using this approach, we can still include the mixed-effects models in
@sharma_2007 using only the fixed-effects estimates, but we flag the model with
the `fixed_only` argument to maintain clarity.

## Implementing a Mixed Effects Model

`predict_fn` *must* be a function of covariates, parameters and observations 
from the target observation group. Furthermore the body of `predict_fn` can 
only be a signle mathematical expression.
